class_name GameEnums
extends RefCounted

enum DamageType {NONE, FIRE, ICE, WATER, LIGHTNING, EARTH, STEAM, ARCANE, 
				SHADOW, CURSE, TOXIC, BLUNT, PIERCE, SLASH, COUNT}
enum GameState {NONE, TITLE, GAMEPLAY, STORE, LEVEL_EDITOR, PAUSE, CUTSCENE,
				COMPLETED, LOST, FADE_IN, FADE_OUT, SWITCH, NEW_SCENE, COUNT}

